<?php //include 'inc/globalvars.php'; ?>
<!-- <h1>TERMS OF USE</h1>
<h3 class="text-left">Acceptance of Terms</h3>
<p>The websites located at healthcare-quotes.com, is a copyrighted work belonging to HCI Compare LLC. Certain features of the Site may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into these Terms.</p>
<p>THESE TERMS OF USE (THESE “TERMS”) SET FORTH THE LEGALLY BINDING TERMS AND CONDITIONS THAT GOVERN YOUR USE OF THE SITE. BY ACCESSING OR USING THE SITE, YOU ARE ACCEPTING THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY OR OTHER PERSON THAT YOU REPRESENT), AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THESE TERMS (ON BEHALF OF YOURSELF OR THE ENTITY OR OTHER PERSON THAT YOU REPRESENT). YOU MAY NOT ACCESS OR USE THE SITE OR ACCEPT THE TERMS IF YOU ARE NOT AT LEAST 18 YEARS OLD OR DO NOT RESIDE IN THE UNITED STATES OF AMERICA. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS, DO NOT ACCESS AND/OR USE THE SITE.</p>
<p>THESE TERMS REQUIRE THE USE OF ARBITRATION (SECTION 11.2) ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS, AND ALSO LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.</p>
<h3 class="text-left">1. Background; Certain Required Information</h3>
<p>1.1 Background. We built healthcare-quotes.com to be an online resource for consumers seeking to make health insurance and other healthcare purchase decisions. We provide search, comparison and other tools to help consumers make smarter choices about their healthcare expenditures. Some of our visitors may, in addition to browsing through the Site, elect to ask us questions about the purchase of health insurance or healthcare products or services, or find an insurance company that can address their needs. We gather information from a variety of data sources including the government, nonprofit and leading commercial resources. You agree that healthcare-quotes.com is in no way responsible for the accuracy, timeliness or completeness of any information it may display or provide. While healthcare-quotes.com provides you the opportunity to receive insurance quotations from our network of service providers (such service providers and any lead aggregators or other third parties to whom your Information (as defined in our Privacy Policy) may be sold or transferred are together, “Network Partners”), healthcare-quotes.com is not a health insurer and does not provide any of the insurance products or services advertised on the Site. We may provide users with the opportunity to submit requests for information on a wide variety of products and services offered by certain Network Partners (each such request, a “Request”). Once you provide us with the information required on our forms, we attempt to match you with Network Partners to help you acquire the type of product or service you are seeking. We are not an insurance carrier and do not act as an insurance agent or broker on the Site, and hence, we do not issue insurance contracts or bind coverage ourselves, nor do we endorse or recommend any companies or specific types of insurance policies.</p>
<p>1.2 Provision of Information. In order to access or use certain features or services offered on the Site, you must provide certain information about yourself as prompted by the webforms displayed to you. You represent and warrant that: (a) all required information you submit is truthful and accurate; (b) you are the person described in such information or, if not, you are lawfully authorized to provide such Information and to give the consent of the person described in such information, including consent to be contacted as required by the Telephone Consumer Protection Act of 1991 47 U.S.C. 227 (“TCPA”); and (c) you will maintain the accuracy of such information. healthcare-quotes.com may suspend or terminate your access to the site and /or any services made available on the Site in accordance with Section 9. If you access the Site on behalf of another person then “you”, “yourself”, “your” and “user” means and refers to you on behalf of yourself and you on behalf of such other person.</p>
<h3 class="text-left">2. Access to the Site</h3>
<p>2.1 License. Subject to these Terms, healthcare-quotes.com grants you a non-transferable, non-exclusive, revocable, limited license to use and access the Site solely for your own personal, noncommercial use.</p>
<p>2.2 Certain Restrictions. The rights granted to you in these Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, whether in whole or in part, or any content displayed on the Site; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive website, product, or service; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms. All copyright and other proprietary notices on the Site (or on any content displayed on the Site) must be retained on all copies thereof.</p>
<p>2.3 Modification. healthcare-quotes.com reserves the right, at any time, to modify, suspend, or discontinue the Site (in whole or in part) with or without notice to you. You agree that healthcare-quotes.com will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Site or any part thereof.</p>
<p>2.4 No Support or Maintenance. You acknowledge and agree that healthcare-quotes.com will have no obligation to provide you with any support or maintenance in connection with the Site.</p>
<p>2.5 Ownership. Excluding any User Content that you may provide (defined below), you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Site and its content are owned by healthcare-quotes.com or healthcare-quotes.com’s suppliers. Neither these Terms (nor your access to the Site) transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in Section 2.1. healthcare-quotes.com and its suppliers reserve all rights not granted in these Terms. You further agree and acknowledge that (i) healthcare-quotes.com will own any Information (as defined in healthcare-quotes.com’s Privacy Policy) you provide when accessing the Site or using the services made available on the site or that healthcare-quotes.com otherwise obtains in connection with your access to and use of the Site and the services; and (ii) healthcare-quotes.com may deal with such Information in any manner including selling such Information to healthcare-quotes.com’s Network Partners provided, however, that healthcare-quotes.com’s use of such Information must be compliant with the healthcare-quotes.com Privacy Policy and these Terms. There are no implied licenses granted under these Terms.</p>
<p>2.6 Requests. In submitting a Request to us, you agree to allow us to refer all of the information that you provide in connection with your request to our Network Partners. If any Network Partner(s) wish to provide information to you in connection with your Request, you will be contacted regarding the offerings and related pricing. We may request that the Network Partners make contact with you via the preferred medium that you have listed, but this does not prevent such Network Partners from contacting you by any other means that they deem appropriate. In working with Network Partners, we seek to work with companies that are reputable, professional and can service the needs of our users. However, we strongly recommend that you perform your own due diligence and research on each potential Network Partner prior to selecting or entering into any agreement or arrangement with any particular Network Partner. In addition, once we refer your request to the Network Partners, we have no further involvement in, or responsibility for, any transactions that occur between you and the Network Partner(s). We are not responsible or liable for ANY expenses, losses or damages (financial or otherwise) incurred in any such transactions or Network Partner’s acts or omissions including, without limitation, with respect to any quotes or services that any such Network Partner may provide, for such Network Partner’s contact or delay or failure to contact you, for such Network Partner’s performance or failure to perform, or for any agreement or transaction between you and any such Network Partner. We cannot and do not guarantee that the Network Partners will provide information for every Request received or that the Network Partners who do respond to your Request can in fact meet your requirements. We may reject any Request and / or elect not to forward a Request to participating Network Partners at our sole discretion.</p>
<h3 class="text-left">3. Privacy</h3>
<p>Your use of the Site, and any Information you provide to us while using the Site, is subject to our Privacy Policy. By using the Site, you consent to the use of your Information as we outline in our Privacy Policy. If we connect you with a Network Partner through the Site or a phone number displayed on the Site, or by any other means, you accept that:</p>
<p>3.1 healthcare-quotes.com makes money when we allow a Network Partner, for example, an insurance company or licensed broker, to help you with an insurance inquiry or when we sell your Information to a Network Partner. We ourselves do not sell insurance.</p>
<p>3.2 Our Privacy Policy governs anything you do on the Site and the applicable Network Partner’s privacy policy governs anything you do (e.g. discuss insurance) with such Network Partner.</p>
<p>3.3 healthcare-quotes.com’s display on or through the Site of healthcare, health insurance products or service options offered by third parties does not in any way imply, suggest, or constitute any sponsorship or approval by healthcare-quotes.com of any such third party (including any Network Partner) or any affiliation between any such third party and healthcare-quotes.com. healthcare-quotes.com’s display of specific options does not suggest a recommendation by healthcare-quotes.com of the Network Partners or their product/service options. You agree that healthcare-quotes.com is in no way responsible for the accuracy, timeliness or completeness of information it may obtain from the Network Partners or elsewhere. Your interaction with any Network Partners accessed through the Site is at your own risk, and healthcare-quotes.com will have no liability with respect to the acts, omissions, errors, representations, warranties, breaches or negligence of any such Network Partners or for any expenses, losses or damages (financial or otherwise) resulting from your interactions with the Network Partners.</p>
<p>3.4 If we display the telephone number of a Network Partner, transfer your phone call to a Network Partner, or link to a Network Partner’s website, any and all contact with such Network Partner is undertaken at your own risk. You, not healthcare-quotes.com, are responsible for any personal information you provide to another company and we recommend as a general practice that you read a company’s privacy policy prior to sharing any personal information.</p>
<h3 class="text-left">4. User Content</h3>
<p>4.1 User Content. “User Content” means any and all information and content that a user submits to, or uses with, the Site (e.g., a user’s postings). You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that personally identifies you or any third party. You hereby represent and warrant that your User Content does not violate our Acceptable Use Policy (defined in Section 4.3). You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by healthcare-quotes.com. Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy. healthcare-quotes.com is not obligated to backup any User Content, and your User Content may be deleted at any time without prior notice. You are solely responsible for creating and maintaining your own backup copies of your User Content if you desire.</p>
<p>4.2 License. You hereby grant (and you represent and warrant that you have the right to grant) to healthcare-quotes.com an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use and exploit your User Content, and to grant sublicenses of the foregoing rights, solely for the purposes of including your User Content in the Site. You hereby irrevocably waive (and agree to cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content.</p>
<p>4.3 Acceptable Use Policy. The following terms constitute our “Acceptable Use Policy”:</p>
<p>(a) You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (i) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (ii) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive, promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual or is otherwise objectionable; (iii) that is harmful to minors in any way; or (iv) that is in violation of any law, regulation, or obligations or restrictions imposed by any third party.</p>
<p>(b) In addition, you agree not to: (i) upload, transmit, or distribute to or through the Site any computer viruses, worms, or any software intended to damage or alter a computer system or data; (ii) send through the Site unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (iii) use the Site to harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (iv) interfere with, disrupt, or create an undue burden on servers or networks connected to the Site, or violate the regulations, policies or procedures of such networks; (v) attempt to gain unauthorized access to the Site (or to other computer systems or networks connected to or used together with the Site), whether through password mining or any other means; (vi) harass or interfere with any other user’s use and enjoyment of the Site; or (vi) use software or automated agents or scripts to produce multiple accounts on the Site, or to generate automated searches, requests, or queries to (or to strip, scrape, or mine data from) the Site (provided, however, that we conditionally grant to the operators of public search engines revocable permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials, subject to the parameters set forth in our robots.txt file).</p>
<p>4.4 Enforcement. We reserve the right (but have no obligation) to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate the Acceptable Use Policy or any other provision of these Terms or otherwise create liability for us or any other person. Such action may include removing or modifying your User Content, terminating your access to or use of the Site and/or services made available on the Site in accordance with Section 9, and/or reporting you to law enforcement authorities.</p>
<p>4.5 Feedback. If you provide healthcare-quotes.com with any feedback or suggestions regarding the Site (“Feedback”), you hereby assign to healthcare-quotes.com all rights in such Feedback and agree that healthcare-quotes.com shall have the right to use and fully exploit such Feedback and related information in any manner it deems appropriate. healthcare-quotes.com will treat any Feedback you provide to healthcare-quotes.com as non-confidential and non-proprietary. You agree that you will not submit to healthcare-quotes.com any information or ideas that you consider to be confidential or proprietary.</p>
<h3 class="text-left">5. Indemnification.</h3>
<p>You agree to indemnify and hold healthcare-quotes.com (and its officers, employees, and agents) harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Site, (b) your violation of these Terms, (c) your violation of applicable laws or regulations or (d) your User Content. healthcare-quotes.com reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of healthcare-quotes.com. healthcare-quotes.com will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
<h3 class="text-left">6. Our Content; Third-Party Links & Ads; Other Users</h3>
<p>6.1 Our Content. healthcare-quotes.com provides the content appearing on the Site solely for your convenience and informational purposes, and such Site content (i) is not intended as a substitute for professional or financial advice; (ii) should not be construed as the provision of professional advice or recommendations; and (iii) should not be relied upon as the basis for any decision or action, including without limitation the diagnosis or treatment of any health problem, the eligibility for or appropriateness of any benefit or service, or the making of a financial decision. We are not responsible for the accuracy or reliability of any Site content, or for expenses, losses or damages (financial or otherwise) incurred by relying upon the information presented on the Site. The information and features included in the Site have been compiled from a variety of sources for informational purposes, and are subject to change at any time without notice.</p>
<p>6.2 No Professional Advice. By accessing or linking to the Site, you assume the risk that the information on the Site may be incomplete, inaccurate, out of date, or may not meet your needs and requirements. It is your responsibility to evaluate the accuracy, completeness, or usefulness of any content available through the Site. The relationship between you and us is not a professional or similar relationship. Always seek the advice of a qualified professional with respect to any questions that you may have, and never disregard professional advice or postpone seeking it because of something that you have read on the Site. We neither recommend nor endorse any specific products, services, opinions, or other content that may be made available through or mentioned on the Site.</p>
<p>6.3 Third-Party Links & Ads. The Site may contain links to third-party websites and services, and/or display advertisements for third parties (collectively, “Third-Party Links & Ads”). Such Third-Party Links & Ads are not under the control of healthcare-quotes.com, and healthcare-quotes.com is not responsible for any Third-Party Links & Ads. healthcare-quotes.com provides access to these Third-Party Links & Ads only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links & Ads. You use all Third-Party Links & Ads at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links & Ads, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third-Party Links & Ads.</p>
<p>6.4 Other Users. Each Site user is solely responsible for any and all of its own User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others. We make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content. Your interactions with other Site users are solely between you and such users. You agree that healthcare-quotes.com will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Site user, we are under no obligation to become involved.</p>
<h3 class="text-left">7. Disclaimers</h3>
<p>THE SITE IS PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS, AND healthcare-quotes.com (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WE (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SITE WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE. IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SITE, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
<h3 class="text-left">8. Limitation on Liability</h3>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL healthcare-quotes.com (OR OUR NETWORK PARTNERS OR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST DATA, COSTS OF PROCUREMENT OF SUBSTITUTE PRODUCTS, OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SITE, EVEN IF healthcare-quotes.com HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SITE IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO A MAXIMUM OF ONE HUNDRED FIFTY US DOLLARS (U.S. $150). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT. TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AGREE THAT OUR NETWORK PARTNERS AND SUPPLIERS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</p>
<h3 class="text-left">9. Term and Termination.</h3>
<p>Subject to this Section, these Terms will remain in full force and effect while you use the Site or any services offered on the Site. For avoidance of doubt, these terms will apply to any interaction you may have with our Network Partners after using the Site or services offered on the Site. We may suspend or terminate your rights to use the Site at any time for any reason at our sole discretion, including for any use of the Site in violation of these Terms. Upon termination of your rights under these Terms, your right to access and use the Site will terminate immediately. You understand that we may delete your User Content in connection with any termination of your rights under these Terms. healthcare-quotes.com will not have any liability whatsoever to you for any termination of your rights under these Terms, including for deletion of your User Content. Even after your rights under these Terms are terminated, the following provisions of these Terms will remain in effect: Sections 2.2 through 2.6 and Sections 4 through 11.</p>
<h3 class="text-left">10. General</h3>
<p>10.1 Changes. These Terms are subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any), and/or by prominently posting notice of the changes on our Site. You are responsible for providing us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice or posting of the revised terms on the Site will nonetheless constitute effective notice of the changes described in the notice. Any changes to these Terms will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our Site. These changes will be effective immediately for new users of our Site. Continued use of our Site following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>
<p>10.2 Dispute Resolution. Please read this Arbitration Agreement carefully. It is part of your contract with healthcare-quotes.com and affects your rights. It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.</p>
<p>(a) If, for some reason, a Dispute (defined below) arises (i) between you and healthcare-quotes.com; and/or (ii) between you and any of our Network Partners in connection with your use of the Site, you, healthcare-quotes.com and each of healthcare-quotes.com’s Network Partners agree to try and resolve such Dispute in good faith. If the Dispute cannot be resolved, you, healthcare-quotes.com and/or each of healthcare-quotes.com’s Network Partners (who have provided their separate agreement to arbitrate any Disputes) agree that we will resolve the Dispute through individual binding arbitration in a non-representative capacity.</p>
<p>(b) Mandatory Arbitration and Waiver of Class Action</p>
<p>(i) Instead of suing in court, you, healthcare-quotes.com and each of healthcare-quotes.com’s Network Partners are waiving the right to a trial by jury or to participate in a class action or representative action. You agree that, by entering into this Agreement, you, healthcare-quotes.com and each of healthcare-quotes.com’s Network Partners are waiving the right to a trial by jury or to participate in a class action or representative action. This agreement to arbitrate is intended to be broadly interpreted and expressly includes any claims brought under or in connection with the TCPA.</p>
<p>(ii) In arbitration, there is no judge or jury. Instead, a neutral third-party arbitrator resolves disputes in a less formal process than in court. In arbitration, there is limited discovery and a court review of the arbitrator’s decision is limited. However, just as a court would, the arbitrator must follow the terms of the Agreement, and can award damages and relief, including attorney’s fees authorized by law.</p>
<p>(c) Disputes include but are not limited to any claims or controversies against each other or in any way arising out of your use of the Site or our services or the agreement between us, including our or our Network Partners use of Information provided by you, attempts made to contact you by us or our Network Partners or calls, emails, text messages or faxes you actually receive from us or our Network Partners, our policies, and contract practices and service, privacy or advertising claims, even if the claim arises after your use of the Site or the services offered on the Site has terminated. Disputes also include, but are not limited to, claims that: (a) you or an authorized or unauthorized user of the services or Site bring against our employees, agents, affiliates, or other representatives; (b) you bring against a third party, such as a Network Partner, that are based on, relate to, or arise out of in any way our services or the agreement between us, but only to the extent we are or become a named party in such dispute; or (c) that we or our Network Partners bring against you, but only to the extent we are or become a named party in such dispute. Disputes also include, but are not limited to, (i) claims in any way related to or arising out of the foregoing matters whether based in contract, tort, statute (expressly including any claims under or in connection with the TCPA), fraud, misrepresentation, advertising claims or any other legal theory; (ii) claims that arose before this Agreement or out of a prior agreement with healthcare-quotes.com; (iii) claims that are subject to ongoing litigation where you are not a party or class member; and/or (iv) claims that arise after the termination of this agreement.</p>
<p>(d) Before a you, healthcare-quotes.com or a Network Partner may seek arbitration, the party must first send the others a written notice of Dispute (a “Notice”) describing the nature and basis of the claim or Dispute and the requested relief. Any Notice to healthcare-quotes.com should be sent to the address set forth in Section 11.7, below. You agree that healthcare-quotes.com may forward the Notice to the relevant Network Partner. After the Notice is received, the parties may attempt to resolve the Dispute informally. If the Dispute is not resolved within thirty (30) days of the Notice, any party may initiate an arbitration.</p>
<p>(e) Unless you, healthcare-quotes.com and, where relevant, any Network Partner, agree otherwise, the arbitration will be conducted by a single, neutral arbitrator and will take place in the capital city of the state in which you resided at the time you used accessed the Site and/or used the services offered on the Site. The arbitration will be governed by either: (a) rules that we mutually agree upon; or (b) the JAMS Comprehensive Arbitration Rules & Procedures (the “JAMS Rules”), as modified by this agreement to arbitrate, including the rules about the filing, administration, discovery and arbitrator fees. The JAMS rules are available on its website at www.jamsadr.com. Notwithstanding any JAMS Rule to the contrary or any other provision in arbitration rules chosen, by agreement, to govern the arbitration, we each agree that all issues regarding the Dispute are delegated to the arbitrator to decide, except that only a court (and not the arbitrator) shall decide any disagreements regarding the scope and enforceability of this agreement to arbitrate.</p>
<p>(f) The Federal Arbitration Act (“FAA”) applies to this agreement and this arbitration provision. We each agree that the FAA’s provisions—not state law—govern all questions of whether a Dispute is subject to arbitration. To the extent that this agreement to arbitrate conflicts with the JAMS Policy on Consumer Arbitrations Pursuant to Pre-Dispute Clauses Minimum Standards for Procedural Fairness (the “Minimum Standards”), the Minimum Standards in that regard will apply. However, nothing in this paragraph will require or allow you, healthcare-quotes.com or a Network Partner to arbitrate on a class-wide, representative or consolidated basis.</p>
<p>(g) The arbitrator may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. YOU, healthcare-quotes.com AND EACH NETWORK PARTNER AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A CLASS MEMBER IN ANY PUTATIVE CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you, healthcare-quotes.com and any applicable Network Partner expressly agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding. If any portion of this provision is found to be unenforceable, then the entirety of this arbitration provision shall be null and void.</p>
<p>(h) You, healthcare-quotes.com and any applicable Network Partner are each responsible for their respective costs, including counsel, experts, and witnesses. healthcare-quotes.com or the applicable Network Partner will pay for any filing or case management fees associated with the arbitration and the professional fees for the arbitrator’s services.</p>
<p>(i) An arbitrator’s award will be a written statement of the disposition of each claim and will also provide a concise written statement of the essential findings and conclusions which form the basis of the award. The arbitrator’s decision and award is final and binding, with some limited court review under the FAA, and judgment on the award may be entered in any court with jurisdiction.</p>
<p>(j) As an alternative to arbitration, we may resolve Disputes in small claims court in the county where you resided at the time you accessed the Site and/or used the services offered on the Site. In addition, this arbitration agreement does not prevent you from bringing your Dispute to the attention of any federal, state, or local government agency. Such agencies can, if the law allows, seek relief against healthcare-quotes.com on your behalf.</p>
<p>(k) IF FOR ANY REASON A CLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT IN ANY WAY PROCEEDS IN COURT RATHER THAN IN ARBITRATION, REGARDLESS OF WHETHER THE CLAIM IS AN ACTION, COUTERCLAIM OR ANY OTHER COURT PROCEEDING, WE EACH AGREE THAT TO THE EXTENT ALLOWED BY LAW, THERE WILL NOT BE A JURY TRIAL OR CLASS ACTION AND WE EACH UNCONDITIONALLY (1) WAIVE ANY RIGHT TO TRIAL BY JURY AND (2) WAIVE ANY RIGHT TO PURSUE DISPUTES ON A CLASSWIDE BASIS, INCLUDING JOINING A CLAIM WITH THE CLAIM OF ANY OTHER PERSON OR ENTITY OR ASSERTING A CLAIM IN A REPRESENTATIVE CAPACTITY ON BEHALF OF ANYONE ELSE IN ANY OTHER PROCEEDING.</p>
<p>10.3 Export. The Site may be subject to U.S. export control laws and may be subject to export or import regulations in other countries. You agree not to export, reexport, or transfer, directly or indirectly, any U.S. technical data acquired from healthcare-quotes.com, or any products utilizing such data, in violation of the United States export laws or regulations.</p>
<p>10.4 Electronic Communications. Communications between you and healthcare-quotes.com may use electronic means, whether you use the Site or send us emails, or whether healthcare-quotes.com posts notices on the Site or communicates with you via email. For contractual purposes, you (a) consent to receive communications from healthcare-quotes.com in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that healthcare-quotes.com provides to you electronically satisfy any legal requirement that such communications would satisfy if they were a hardcopy in writing. The foregoing does not affect your non-waivable rights.</p>
<p>10.5 Entire Terms. These Terms constitute the entire agreement between you and us regarding the use of the Site. Our failure to exercise or enforce any right or provision of these Terms shall not operate as a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation”. Except as otherwise expressly set forth herein, if any provision of these Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Your relationship to healthcare-quotes.com is that of an independent contractor, and neither party is an agent or partner of the other. These Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without healthcare-quotes.com’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. healthcare-quotes.com may freely assign these Terms. The terms and conditions set forth in these Terms shall be binding upon assignees.</p>
-->
<!-- Replaced 05/18/26
 <h1>TERMS OF USE</h1>

<p><strong>Last Modified: 1.1.22</strong></p>
<p>These Terms of Use ("Terms") apply to and govern your access to and use of any website, mobile site or app, social media site, software, applications, email exchange of information, and any other digital platform, including any services, features, pages, and functions contained or offered therein, including any transactions, orders, sales, purchases, or the acquisition of goods or services (collectively the "Service"), that are owned, operated, or provided by HCI Compare LLC. or its subsidiaries, divisions, and affiliates  ("HCI Compare LLC", "we", "our" or "us").</p>
<p>HCI Compare LLC offers the Service, including all information, tools, services, goods, and products available through the Service, to you, conditioned upon your acceptance of all terms, conditions, policies, and notices stated herein or incorporated by reference. Please read these Terms carefully before using our Service or making any transaction, order or purchase. By making any transaction, order or purchase or by visiting or otherwise using our Service, you acknowledge, accept, and agree to be bound and abide by these Terms. You also acknowledge, agree, and consent to our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a> which is incorporated herein by reference. If you do not agree to these Terms or our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>, then accessing the Service is strictly prohibited, and you must immediately exit.</p>
<p>By using the Service, you agree that you are at least the legal age of majority in the jurisdiction in which you reside or, if you are not, that you have obtained parental or guardian consent. The Service is only offered and available to users who are at least eighteen (18) years of age or older. IF YOU ARE UNDER THE AGE OF EIGHTEEN (18) YOU ARE NOT AUTHORIZED TO USE THE SERVICE.</p>
<p>We reserve the right to change these Terms at any time and at our sole discretion. Any changes to the Terms will be effective immediately upon posting and you agree to the new posted Terms by continuing your use of the Service. It is your responsibility to check periodically for any changes we may make to these Terms.</p>
<p>THESE TERMS AFFECT YOUR LEGAL RIGHTS, RESPONSIBILITIES, AND OBLIGATIONS, GOVERN YOUR USE OF THE SERVICE, ARE LEGALLY BINDING, LIMIT HCI Compare LLC'S LIABILITY TO YOU, AND REQUIRE YOU TO INDEMNIFY HCI Compare LLC AND TO SETTLE CERTAIN DISPUTES THROUGH ARBITRATION. YOUR CONTINUED USE OF THE SERVICE AFFIRMS YOUR AGREEMENT TO THESE TERMS. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS OR ANY FUTURE MODIFICATIONS OR AMENDMENTS TO THESE TERMS, DO NOT USE OUR SERVICE.</p>
<p>These Terms are written in the English language. We do not guarantee the accuracy of any translated versions of these Terms. To the extent any translated versions of these Terms conflict with the English language version, the English language version of these Terms shall control.</p>

<p><strong>Accuracy of Information and Reliance on Information Posted</strong></p>
<p>We built the Service to be a resource for consumers seeking to make health insurance and other healthcare purchase decisions. We provide search, comparison, and other tools to help consumers make smarter choices about their healthcare expenditures. Some of our customers may, in addition to browsing through our website, elect to ask us questions about the purchase of health insurance or healthcare products or services, or find an insurance company that can address their needs. To answer these questions, we gather information from a variety of data sources including the government, nonprofit and leading commercial resources.</p>
<p>The information presented on or through the Service is made available solely for general information purposes, is not intended as a substitute for professional or financial advice, and should not be construed as the provision of professional advice or recommendations. HCI Compare LLC attempts to ensure that information on this Service is complete, accurate, and current. However, despite our efforts, the information on the Service may occasionally be inaccurate, incomplete, or out of date. Thus, the Service may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only.</p>
<p>Accordingly, we do not warrant the completeness, accuracy, timeliness, or usefulness of any information on this Service, and you should not rely upon or use such information as the sole basis for making decisions or taking any action without consulting primary, more accurate, more complete, or more timely sources of information. Any reliance on the material on the Service is strictly at your own risk. We reserve the right to modify the contents of the Service at any time, but we have no obligation to update any information on our Service. You agree that it is your responsibility to monitor changes to our Service and to evaluate the accuracy, completeness, or usefulness of any content available through the Service. Always seek the advice of a qualified professional with respect to any questions that you may have, and never disregard professional advice or postpone seeking it because of something that you have read on the Service.</p>
<p>While HCI Compare LLC provides you the opportunity to receive insurance quotations from insurance agents, insurance carriers, lead aggregators, and other insurance service providers and third parties in our network that provide services to our users (collectively, "Network Partners"), by using the Service you understand and agree that HCI Compare LLC is not a health insurer or insurance carrier and does not provide any of the insurance products or services advertised on the Service or act as an insurance agent or broker. We do not issue insurance contracts or bind coverage ourselves, nor do we endorse or recommend any companies or specific types of insurance policies. We may provide you with the opportunity to submit requests for information on a wide variety of products and services offered by certain Network Partners (each a "Request"). Once you provide us with the information required on our forms, we attempt to match you with Network Partners to help you acquire the type of product or service you are seeking.</p>
<p>We disclaim all liability and responsibility arising from any reliance placed on any materials or information by you or any other visitor to the Service, or by anyone who may be informed of any of its contents. This Service may include content provided by third parties. All statements and opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by the HCI Compare LLC, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of the HCI Compare LLC. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</p>

<p><strong>Requests</strong></p>
<p>By submitting a Request, you agree to allow us to refer the information that you provide to our Network Partners and that, if any Network Partners wish to provide information to you in connection with your Request, you will be contacted by such Network Partners regarding the offerings and related pricing.</p>
<p>We may request that the Network Partners make contact with you via the preferred medium that you have listed, but this does not prevent such Network Partners from contacting you by any other means that they deem appropriate. In working with Network Partners, we seek to work with companies that are reputable, professional and can service the needs of our users. However, we strongly recommend that you perform your own due diligence and research each potential Network Partner prior to selecting or entering into any agreement or arrangement with any particular Network Partner.</p>
<p>Once we refer your Request to a Network Partner, you acknowledge and agree that we have no further involvement in, or responsibility for, any transactions that occur between you and such Network Partner. We are not responsible or liable for any expenses, losses, or damages (financial or otherwise) incurred in any such transactions or as a result of any Network Partner's acts or omissions including, without limitation, with respect to any quotes or services that any such Network Partner may provide, for such Network Partner's contact or delay or failure to contact you, for such Network Partner's performance or failure to perform, or for any agreement or transaction between you and any such Network Partner. We cannot and do not guarantee that Network Partners will provide information for every Request received or that Network Partners who do respond to your Request can in fact meet your requirements. We reserve the right to reject any Request and elect not to forward a Request to participating Network Partners at our sole and absolute discretion.</p>

<p><strong>Accessing the Service</strong></p>
<p>We also reserve the right to withdraw or amend our Service at our sole discretion and without notice. We will not be liable if for any reason all or any part of the Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Service, or the entire Service, to users.</p>
<p>To access the Service, you may be asked to provide information about yourself. It is a condition of your use of the Service that all the information you provide on the Service is correct, current, and complete. You agree that all information you provide to access or use this Service, including, but not limited to, through the use of any interactive features or webforms on the Service, is governed by our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>, and you consent to all actions we take with respect to your information consistent with our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>. You also agree that you are the person described in the information you provide.</p>
<p>YOU ARE SOLELY RESPONSIBLE FOR ALL ACCESS TO AND USE OF THE SERVICE BY ANYONE USING YOUR IDENTIFICATION WHETHER OR NOT SUCH ACCESS TO AND USE OF THE SERVICE IS ACTUALLY AUTHORIZED BY YOU, INCLUDING WITHOUT LIMITATION, ALL COMMUNICATIONS, TRANSMISSIONS, AND OTHER OBLIGATIONS INCURRED THROUGH SUCH ACCESS OR USE.</p>

<p><strong>Intellectual Property Rights and Ownership of Service</strong></p>
<p>The Service and its entire contents, features, and functionality, including without limitation all information, copyrights, patents, trademarks, service marks, and trade names, as well as all logos, text, design, graphics, displays, video, logos, icons, images, audio, downloads, interfaces, code, and software, as well as the selection and arrangement thereof, and all other intellectual property (collectively, the "Content"), are all proprietary and owned or controlled by HCI Compare LLC, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws to the fullest extent possible.</p>
<p>These Terms permit you to use the Service and Content for your personal, non-commercial use only. A limited, revocable, nontransferable license is granted to temporarily download one copy of the Content for personal, non-commercial transitory viewing only. This is not a transfer of title, right, or interest in the Service or Content. The license does not give you the right to, and you are strictly prohibited from, copying the Content, modifying the Content, using the Content for any commercial purpose, publicly displaying the Content, attempting to decompile or reverse engineer the Content, removing any copyright, trademark, or other proprietary notations from the Content, or otherwise infringing upon the intellectual property rights of HCI Compare LLC or its licensors. This license shall automatically terminate if you violate any of these restrictions, or any provision of the Terms, and may be terminated by HCI Compare LLC at any time for any or no reason. Upon termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format. Except as expressly provided in these Terms, no assignments or license of intellectual property are granted by HCI Compare LLC.</p>
<p>HCI Compare LLC owns and uses several trademarks on the Service and all related names, logos, product and service names, designs, and slogans. You must not use such marks without the prior written permission of the HCI Compare LLC. All other names, logos, product and service names, designs, and slogans on the Service are the trademarks of their respective owners. </p>

<p><strong>Linking to Our Service</strong></p>
<p>Creating or maintaining any link to any page or portion of the Service, or running or displaying this Service or any Content in any format without HCI Compare LLC's prior written permission, is strictly prohibited. Any permitted links to this Service must comply will all applicable laws, rules, and regulations.</p>
<p>In the event you are permitted to link to this Service, you must also do so in a way that is fair and legal and complies with our Terms, does not damage our reputation or take advantage of it, and does not suggest any form of association, approval, or endorsement on our part. The website from which you are linking, or on which you make certain content accessible, must comply in all respects with the Content Standards set out in these Terms.</p>
<p>You agree to cooperate with us in immediately ceasing any unauthorized display or linking of our Service or Content. We reserve the right to withdraw permission without notice, and we may disable all or any social media features and any links at any time without notice in our discretion.</p>

<p><strong>Linked Sites</strong></p>
<p>The Service may provide links to other third-party websites ("Linked Sites"). HCI Compare LLC has not reviewed all of the information on the Linked Sites, does not maintain Linked Sites, and cannot control the completeness, accuracy, or security of the content contained on any Linked Site. The content of, including materials and information contained on, any Linked Site is solely the responsibility of the provider of that Linked Site. HCI Compare LLC is not responsible for the contents of any such Linked Site, and the inclusion of any link to a Linked Site does not imply endorsement by HCI Compare LLC of the Linked Site. The views and opinions expressed in Linked Sites are those of the authors or third parties and do not necessarily reflect the official policy or position of HCI Compare LLC. If you decide to access any Linked Site, you do this entirely at your own risk. References to any names, marks, products, or services of any third parties, third-party information, or Linked Sites are provided solely as a convenience to you, and do not constitute or imply an endorsement, sponsorship, recommendation of, or affiliation with, the third party or its products and services. HCI Compare LLC makes no representation or warranty as to any Linked Site content, products, or services, and you agree that HCI Compare LLC shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such third-party content, products, or services available on or through any Linked Site or similar resource.</p>
<p>AS PERMITTED BY APPLICABLE LAW, WE SHALL UNDER NO CIRCUMSTANCES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL OR SPECIAL LOSS, OR OTHER DAMAGE, WHETHER ARISING FROM NEGLIGENCE, BREACH OF CONTRACT, DEFAMATION, INFRINGEMENT OF COPYRIGHT, OR OTHER INTELLECTUAL PROPERTY RIGHTS, CAUSED BY THE EXHIBITION, DISTRIBUTION, OR EXPLOITATION OF ANY INFORMATION OR CONTENT CONTAINED WITHIN THESE THIRD-PARTY SERVICES.</p>

<p><strong>Prohibited Uses</strong></p>
<p>You may use the Service only for lawful purposes and in accordance with these Terms. You agree not to use the Service:</p>
<ul>
  <li>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries).</li>
  <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
  <li>To send, knowingly receive, upload, download, use, or re-use any material that does not comply with the Content Standards set out in these Terms.</li>
  <li>To transmit, or procure the sending of, any advertising or promotional material without our prior written consent, including any "junk mail," "chain letter," "spam," or any other similar solicitation.</li>
  <li>To impersonate or attempt to impersonate the HCI Compare LLC, a HCI Compare LLC employee, another user, or any other person or entity (including, without limitation, by using email addresses or screen names associated with any of the foregoing).</li>
  <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or which, as determined by us, may harm the HCI Compare LLC or users of the Service, or expose them to liability.</li>
</ul>

<p>Additionally, you agree not to:</p>
<ul>
  <li>Use the Service in any manner that could disable, overburden, damage, or impair the site or interfere with any other party's use of the Service, including their ability to engage in real time activities through the Service.</li>
  <li>Use any robot, spider, or other automatic device, process, or means to access the Service for any purpose, including monitoring or copying any of the material on the Service.</li>
  <li>Use any manual process to monitor or copy any of the material on the Service, or for any other purpose not expressly authorized in these Terms, without our prior written consent.</li>
  <li>Use any device, software, or routine that interferes with the proper working of the Service.</li>
  <li>Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</li>
  <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service, the server on which the Service is stored, or any server, computer, or database connected to the Service.</li>
  <li>Attack the Service via a denial-of-service attack or a distributed denial-of-service attack.</li>
  <li>Otherwise attempt to interfere with the proper working of the Service.</li>
</ul>

<p><strong>User Content</strong></p>
<p>The Service may contain interactive features that allow users to post, submit, publish, display, or transmit to HCI Compare LLC, other users or other persons content or materials (collectively, "User Content") on or through the Service. Other than personally identifiable information, which is subject to our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>, any such User Content, including but not limited to any creative material, information, suggestions, ideas, concepts, know-how, techniques, questions, comments, or other communications you transmit or post to or through this Service in any manner, is and will be considered non-confidential and non-proprietary. All User Content must comply with the Content Standards set out in these Terms.</p>
<p>Your User Content may be posted and transmitted to others at your own risk. We cannot control the actions of other users of the Service with whom you may choose to share your User Content. All User Content may be retained by us indefinitely, even after you terminate your account. By submitting any User Content, you grant to HCI Compare LLC a perpetual, worldwide, irrevocable, non-exclusive, royalty-free license to use the User Content in any manner, including to create derivative works, without any compensation or notice to you. By providing any User Content on the Service, you grant us and our affiliates and service providers, and each of their and our respective licensees, successors, and assigns the right to use, reproduce, transmit, publish, broadcast, develop, manufacture, market, modify, perform, display, distribute, and otherwise disclose to third parties any such material for any purpose whatsoever. HCI Compare LLC will have no liability related to any User Content.</p>
<p>You further represent and warrant that:</p>
<ul>
  <li>You own or control all rights in and to the User Content and have the right to grant the license granted above to us and our affiliates and service providers, and each of their and our respective licensees, successors, and assigns.</li>
  <li>All of your User Content do and will comply with these Terms.</li>
  <li>You understand and acknowledge that you are responsible for any User Content you submit or contribute, and you, not the HCI Compare LLC, have full responsibility for such content, including its legality, reliability, accuracy, and appropriateness.</li>
  <li>We are not responsible or liable to any third party for the content or accuracy of any User Content posted by you or any other user of the Service.</li>
</ul>

<p>We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms.</p>
<p>We have the right to:</p>
<ul>
  <li>Remove or refuse to post any User Content for any or no reason in our sole discretion.</li>
  <li>Take any action with respect to any User Content that we deem necessary or appropriate in our sole discretion, including if we believe that such User Content violates the Terms, including the Content Standards, infringes any intellectual property right or other right of any person or entity, threatens the personal safety of users of the Service or the public, or could create liability for the HCI Compare LLC.</li>
  <li>Disclose your identity or other information about you to any third party who claims that material posted by you violates their rights, including their intellectual property rights or their right to privacy.</li>
  <li>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Service.</li>
  <li>Terminate or suspend your access to all or part of the Service for any or no reason, including without limitation, any violation of these Terms.</li>
</ul>

<p>Without limiting the foregoing, we have the right to cooperate fully with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Service. YOU WAIVE AND HOLD HARMLESS HCI Compare LLC AND ITS AFFILIATES, LICENSEES, AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING, OR TAKEN AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</p>
<p>We cannot review all material before it is posted on or through the Service, and cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications, or content provided by any user or third party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section.</p>

<p><strong>Content Standards</strong></p>
<p>These content standards (the "Content Standards") apply to any and all User Content and use of the Service. User Content must in their entirety comply with all applicable federal, state, local, and international laws and regulations. Without limiting the foregoing, User Content must not:</p>
<ul>
  <li>Contain any material that is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory, or otherwise objectionable.</li>
  <li>Promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age.</li>
  <li>Infringe any patent, trademark, trade secret, copyright, or other intellectual property or other rights of any other person.</li>
  <li>Violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations or that otherwise may be in conflict with these Terms and our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>.</li>
  <li>Be likely to deceive any person.</li>
  <li>Promote any illegal activity, or advocate, promote, or assist any unlawful act.</li>
  <li>Cause annoyance, inconvenience, or needless anxiety or be likely to upset, embarrass, alarm, or annoy any other person.</li>
  <li>Impersonate any person or misrepresent your identity or affiliation with any person or organization.</li>
  <li>Involve commercial activities or sales, such as contests, sweepstakes, and other sales promotions, barter, or advertising.</li>
  <li>Give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case.</li>
  <li>Be posted through a false email address, while pretending to be someone other than yourself, or under any other circumstances that could mislead us or third-parties as to the origin of any User Content.</li>
</ul>

<p><strong>Information Collected about You</strong></p>
<p>All information we collect on this Service is subject to our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>. By using the Service, you consent to all actions taken by us with respect to your information in compliance with our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a>.</p>

<p><strong>Geographic Restrictions</strong></p>
<p>HCI Compare LLC is based in the United States; as such, we provide the Service for use only by persons located in the United States. We make no claims that the Service or any of its Content is accessible or appropriate outside of the United States. Access to the Service may not be legal by certain persons or in certain countries. If you access the Service from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</p>

<p><strong>SMS/MMS Mobile Messaging Program</strong></p>
<p>HCI Compare LLC offers a mobile messaging program in connection with its various services (the "Program"), where, by opting into the Program, you agree to these Terms and to receive marketing text messages from us and our affiliates, Network Partners, and their agents (collectively, "Contacts") directly, through the Service, or through third parties such as platform providers, phone companies, and other vendors or service providers who assist us and our Contacts in making phone calls and delivering text messages. The Program is optional and not a condition of purchase of any goods or services.</p>
<p>The Program allows you to receive SMS/MMS mobile messages by voluntarily and affirmatively opting into the Program, such as through online or application-based enrollment forms. The messages we send to you include marketing messages. Service-related messages may include updates, alerts, and other information about the Service. Messaging frequency may vary. You must have a wireless device of your own, capable of two-way messaging, be using a participating wireless carrier, and be a wireless service subscriber with text messaging service. Not all cellular phone providers carry the necessary service to participate. Check your phone capabilities for specific text messaging instructions.</p>
<p>Regardless of the opt-in method you utilized to join the Program, you agree that these Terms apply to your participation in the Program. By participating in the Program, you agree to receive autodialed or prerecorded marketing mobile messages at the phone number associated with your opt-in, and you understand that consent is not required to make any purchase of goods or services from HCI Compare LLC. While you consent to receive messages sent using an autodialer, the foregoing shall not be interpreted to suggest or imply that any or all of HCI Compare LLC's mobile messages are sent using an automatic telephone dialing system ("ATDS" or "autodialer"). Message and data rates may apply. Please consult your mobile service carrier's pricing plan to determine the charges for browsing data and sending and receiving mobile messages. Under no circumstances will we be responsible for any messaging or wireless charges incurred by you or by a person that has access to your wireless device or telephone number.</p>
<p>Data obtained from you in connection with the Program may include your cell phone number, your provider's name and the date, time and content of your text messages. We may use this information in accordance with our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a> to contact you and to provide the services you request from us.</p>

<p><strong>SMS/MMS Mobile Messaging Opt-Out.</strong> If you do not wish to continue participating in the Program, you agree to reply "STOP" to any mobile message from HCI Compare LLC in order to opt out of the Program. You may receive an additional mobile message confirming your decision to opt out. You understand and agree that the foregoing options are the only reasonable methods of opting out. You also understand and agree that any other method of opting out, including, but not limited to, texting words other than those set forth above or verbally requesting one of our employees to remove you from our list, is not a reasonable means of opting out.</p>

<p>Without limiting the scope of the Program, users that opt into the Program can expect to receive messages concerning the marketing and sale of digital and physical products, services, and events. Message and data rates may apply. The Program involves recurring mobile messages, and additional mobile messages may be sent periodically based on your interaction with us. For support regarding the Program, text "HELP" to the number you received messages from or email us at <a href="mailto:hcicompare@gmail.com" target="_blank">hcicompare@gmail.com</a>. Opt-outs should be submitted in accordance with the procedures set forth above.</p>
<p>The Program is offered on an "as-is" basis and may not be available in all areas at all times and may not continue to work in the event of product, software, coverage or other changes made by your wireless carrier. We will not be liable for any delays or failures in the receipt of any mobile messages connected with this Program. HCI Compare LLC and the carriers are not liable for delayed or undelivered mobile messages.</p>
<p>We endeavor to comply with all applicable telemarketing laws, including but not limited to the Telephone Consumer Protection Act ("TCPA"), Florida Telemarketing Act, and Florida Do Not Call Act. For purposes of compliance, you agree that we may assume that you are a resident of a certain state if, at the time of opt-in to Program, (1) your address, as provided, is located in that state or (2) the area code for the phone number used to opt-into the Program is an area code for that state. You agree that the requirements of a state's telemarketing laws do not apply to you, and you shall not assert that you are resident of that state, if you do not meet either of the foregoing criteria or, in the alternative, do not affirmatively advise us in writing that you are a resident of the state by sending written notice to us. You further agree that mobile messages sent by us in direct response to mobile messages or requests from you (including but not limited to response to keywords, opt-in, help or stop requests, and shipping notifications) shall not constitute a "telephonic sales call" or "commercial telephone solicitation phone call" (e.g., for purposes of Florida Statutes Section 501 (including but not limited to sections 501.059 and 501.616)), "telephone solicitation" (e.g., for purposes of the TCPA and state laws such as the Utah Telephone and Facsimile Solicitation Act and Washington Commercial Telephone Solicitation Act), or an otherwise unsolicited call or message that is subject to a telemarketing law, to the extent such laws are relevant and applicable.</p>

<p><strong>MMS Disclosure.</strong> The Program will send SMS TMs (terminating messages) if your mobile device does not support MMS messaging.</p>

<p><strong>Disclaimers and Limitation of Liability</strong></p>
<p>YOUR USE OF THE SERVICE IS AT YOUR RISK. THE SERVICE AND ALL SERVICES, INFORMATION, GOODS, AND MATERIALS MADE AVAILABLE OR PURCHASED THROUGH THE SERVICE ARE PROVIDED TO YOU "AS IS" WITHOUT ANY EXPRESS REPRESENTATIONS OR WARRANTIES OF ANY KIND, AND WE DISCLAIM ALL STATUTORY OR IMPLIED REPRESENTATIONS, WARRANTIES, TERMS, AND CONDITIONS WITH RESPECT TO THE SERVICE AND ALL SERVICES, INFORMATION, GOODS, AND MATERIALS MADE AVAILABLE THROUGH THE SERVICE, INCLUDING THE REPRESENTATIONS AND WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, AND TITLE, AND WITH RESPECT TO THE PRODUCTS LISTED OR PURCHASED ON OR THROUGH THE SERVICE.</p>
<p>WE MAKE NO REPRESENTATION OR WARRANTY THAT THE SERVICE (OR ANY PART THEREOF) WILL BE ACCURATE, COMPLETE, OR ERROR-FREE, NOR THAT ANY PARTICULAR SOFTWARE OR HARDWARE, WILL BE COMPATIBLE WITH THE SERVICE, AND YOU HEREBY AGREE THAT IT IS YOUR SOLE RESPONSIBILITY TO (A) OBTAIN AND PAY FOR ANY SOFTWARE, HARDWARE AND SERVICES (INCLUDING INTERNET CONNECTIVITY) NEEDED TO ACCESS AND USE THE SERVICE AND (B) ENSURE THAT ANY SOFTWARE, HARDWARE, AND SERVICES THAT YOU USE WILL FUNCTION CORRECTLY WITH THE SERVICE. THE MATERIALS ON THE SERVICE MAY BE OUT OF DATE, AND HCI Compare LLC MAKES NO COMMITMENT AND ASSUMES NO DUTY TO UPDATE SUCH MATERIALS. HCI Compare LLC MAKES NO WARRANTY THAT THE SERVICE WILL BE AVAILABLE, UNINTERRUPTED, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT YOU WILL ACHIEVE SUCCESSFUL RESULTS FROM FOLLOWING ANY INSTRUCTIONS OR DIRECTIONS ON THE SERVICE. YOU AGREE THAT YOU MUST EVALUATE, AND THAT YOU BEAR ALL RISKS ASSOCIATED WITH, THE USE OF THE SERVICE, INCLUDING ANY RELIANCE ON THE ACCURACY, COMPLETENESS, TIMELINESS, OR USEFULNESS OF ANY INFORMATION OR MATERIALS MADE AVAILABLE THROUGH THE SERVICE. WITHOUT LIMITING THE FOREGOING, HCI Compare LLC HEREBY EXPRESSLY DISCLAIMS ALL LIABILITY FOR PRODUCT DEFECT OR FAILURE, CLAIMS THAT ARE DUE TO NORMAL WEAR, PRODUCT MISUSE, ABUSE, PRODUCT MODIFICATION, IMPROPER PRODUCT SELECTION, NON-COMPLIANCE WITH ANY CODES, OR MISAPPROPRIATION. HCI Compare LLC MAKES NO WARRANTIES TO THOSE DEFINED AS "CONSUMERS" IN THE MAGNUSON-MOSS WARRANTY ACT. THE FOREGOING EXCLUSIONS OF IMPLIED WARRANTIES DO NOT APPLY TO THE EXTENT PROHIBITED BY LAW.</p>
<p>ADDITIONALLY, IN NO EVENT WILL HCI Compare LLC, ITS RESPECTIVE MEMBERS, EMPLOYEES, AFFILIATES, AGENTS, SUCCESSORS, ASSIGNS, RETAIL PARTNERS, OR ANY PARTY INVOLVED IN THE CREATION, PRODUCTION, OR TRANSMISSION OF THE SERVICE, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND IN CONNECTION WITH THE SERVICE, OR FOR ANY DAMAGES FOR LOSS OF PROFITS, LOSS OF USE, LOSS OF DATA, LOSS OF OTHER INTANGIBLES, BUSINESS INTERRUPTION, LOSS OF SECURITY OF INFORMATION YOU HAVE PROVIDED IN CONNECTION WITH YOUR USE OF THE SERVICE, OR UNAUTHORIZED INTERCEPTION OF ANY SUCH INFORMATION BY THIRD PARTIES, EVEN IF ADVISED IN ADVANCE OF SUCH DAMAGES OR LOSSES. FURTHER, WE WILL NOT BE LIABLE FOR DAMAGES OF ANY KIND RESULTING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, ANY INFORMATION OR MATERIALS ON THE SERVICE, ANY LINKED SITES, OR THE MATERIALS, INFORMATION, OR SERVICES CONTAINED AT ANY OR ALL SUCH LINKED SITES. IN THE EVENT OF ANY PROBLEM WITH THE SERVICE OR ANY CONTENT, YOU AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SERVICE IS TO STOP USING THE SERVICE. MOREOVER, IN THE EVENT OF ANY PROBLEM OR DISSATISFACTION WITH THE PRODUCT THAT YOU HAVE PURCHASED ON OR THROUGH THE SERVICE, YOU AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY, IF ANY, IS TO SEEK A RETURN AND REFUND FOR SUCH PRODUCT IN ACCORDANCE WITH THE RETURN POLICY POSTED ON THE SERVICE. OUR MAXIMUM LIABILITY FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE), OR OTHERWISE SHALL BE THE TOTAL AMOUNT, IF ANY, PAID BY YOU TO US TO ACCESS AND USE THE SERVICE.</p>
<p>IT IS POSSIBLE THAT APPLICABLE LAW MAY NOT ALLOW FOR LIMITATIONS ON CERTAIN IMPLIED WARRANTIES OR EXCLUSIONS OR LIMITATIONS OF CERTAIN DAMAGES; SOLELY TO THE EXTENT THAT SUCH LAW APPLIES TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. IF APPLICABLE LAW PROHIBITS THE LIMITATION OR EXCLUSION OF A PARTY'S LIABILITY WITH RESPECT TO DEATH OR PERSONAL INJURY CAUSED BY SUCH PARTY'S NEGLIGENCE, FRAUD, OR ANY OTHER MATTER, THEN SUCH PARTY'S LIABILITY WILL NOT BE LIMITED OR EXCLUDED TO THE EXTENT OF SUCH PROHIBITION UNDER SUCH APPLICABLE LAW.</p>
<p>If you are a California resident, you agree to consciously waive all claims, both known and unknown that may be later discovered, to the maximum extent permitted by law, including but not limited to that permitted by California Civil Code Section 1542, which states "[a] general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party."</p>

<p><strong>Indemnification</strong></p>
<p>Except to the extent prohibited under applicable law, you agree to indemnify, defend, and hold harmless HCI Compare LLC and its officers, directors, employees, and agents from and against any claims, losses, liabilities, damages, costs, or expenses, including attorneys' fees and costs, that may arise from or in connection with (a) your use of, or activities in connection with, the Service, including use of any good, product, or service purchased through the Service, (b) violation of these Terms by you, including any misrepresentations made by you in connection with your use of the Service (c) your violation of any law or the rights of a third-party, and (d) the acts or omissions of any other user or third-party. If you fail to promptly indemnify and defend a covered claim, HCI Compare LLC shall have the right to defend itself, and in such case, you shall promptly reimburse HCI Compare LLC for all of its associated costs and expenses. HCI Compare LLC reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to your indemnification.</p>

<p><strong>ARBITRATION, CHOICE OF LAW, AND VENUE</strong></p>
<p>Any dispute, claim, or controversy arising out of or relating to these Terms, including the determination of the scope or applicability of this agreement to arbitrate, shall be submitted to and settled exclusively by binding arbitration, in accordance with the provisions of this section, subject only to any applicable requirement of law that you and HCI Compare LLC engage in a preliminary, non-binding mediation or arbitration. Binding arbitration shall be conducted in accordance with the American Arbitration Association's rules (the "AAA Rules"). Arbitration shall be held in Orange County, Florida, and shall be held before an arbitrator selected pursuant to the AAA Rules who shall have no personal or pecuniary interest, either directly or indirectly, from any business or familial relationship with either you or us. The arbitrator(s) shall be bound to adjudicate all disputes in accordance with the laws of the State of Florida and all decisions of the arbitrator will be final, binding, and conclusive on you and HCI Compare LLC. Either you or HCI Compare LLC may seek confirmation of the arbitration award in the Florida state courts in and for Orange County, Florida, and both parties hereby consent to the exclusive jurisdiction and venue of the Florida state courts in and for Orange County, Florida in any claim or action arising under this arbitration provision.</p>
<p>YOU AND WE ALSO AGREE TO WAIVE ANY AND ALL RIGHTS TO A JURY TRIAL. ADDITIONALLY, UNLESS YOU AND WE AGREE OTHERWISE, EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, REPRESENTATIVE ACTION OR PRIVATE ATTORNEY GENERAL PROCEEDING. ALSO, TO THE EXTENT AVAILABLE BY LAW, AND SUBJECT TO THE DAMAGE LIMITATIONS DISCUSSED HEREIN, THE ARBITRATOR MAY AWARD RELIEF ONLY IN FAVOR, AND FOR THE BENEFIT OF, THE INDIVIDUAL PARTY SEEKING RELIEF.</p>
<p>All costs and expenses, including reasonable attorneys' fees and experts' fees, incurred by you or HCI Compare LLC in any dispute that is determined and settled by arbitration or some other proceeding pursuant to these Terms shall be borne by the party determined to be liable in respect to such dispute; provided, however, that if complete liability is not assessed against only one party, then you and HCI Compare LLC will share the total costs in proportion to their respective amounts of liability so determined. Except where clearly prevented by the area in dispute, you and we agree to continue performing their respective obligations under these Terms until the dispute is resolved.</p>
<p>If it is determined that arbitration is not permitted, has been waived, or is otherwise unavailable, then the sole and exclusive jurisdiction and venue for any action or proceeding arising out of or related to these Terms shall be an appropriate state or federal court located in Orange County, Florida. You and HCI Compare LLC hereby submit to the personal jurisdiction of the State of Florida and the jurisdiction and venue of said courts. You and HCI Compare LLC further agree that the laws of the State of Florida, without regard to the principles of conflict of laws, shall govern these Terms and any dispute, claim, or controversy that has arisen or may arise related to these Terms. This paragraph shall not be read to conflict with the mandatory arbitration provision.</p> 

<p><strong>Additional Terms</strong></p>
<p>The failure of HCI Compare LLC of any term or condition set out in these Terms shall not be deemed waiver of such term or condition or a waiver of any other term or condition.</p>
<p>If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms will continue in full force and effect.</p>
<p>These Terms and our <a data-toggle="modal" data-target="#policyModal" style="cursor: pointer;">Privacy Policy</span></a> constitute the sole and entire agreement between you and HCI Compare LLC regarding the Service and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Service. You may be subject to additional terms and conditions when you purchase products or participate in a sweepstakes, contest, or other promotions.</p>
<p>By accessing the Service, you agree that the laws of the United States and the state of Florida without regard to conflicts of laws principles, will apply to these Terms and all matters relating to the Service.</p>
<p>Subject to the arbitration provisions above, and other than small claims actions as permitted therein, any action or proceeding arising from, relating to or in connection with these Terms will be brought exclusively in the federal or state courts located in Orange County, Florida, and you irrevocably consent to the personal jurisdiction of such courts and agree that it is a convenient forum and that you will not seek to transfer such action or proceeding to any other forum or jurisdiction, under the doctrine of forum non conveniens or otherwise.</p>
<p>You agree that regardless of any statute or law that establishes a different statute of limitations, to the maximum extent permitted under applicable law, any claim or cause of action (including any arbitration) arising out of, related to or connected with the use of the Service, or these Terms, or other transactions or relationships must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
<p>We may provide you information regarding your account and the Service in electronic form only. You agree that such notices and other communications sent electronically satisfy any legal communication requirements, including that requirements must be in writing.</p>
-->

<h1>TERMS OF USE</h1>
<p style="text-align:right; font-style: italic;"><small>Last Modified: March 26, 2026</small></p>
<p>These Terms of Use ("Terms") apply to and govern your access to and use of any website, mobile site or app, social media site, software, applications, email exchange of information, and any other digital platform, including any services, features, pages, and functions contained or offered therein, including any transactions, orders, sales, purchases, or the acquisition of goods or services (collectively the "Service"), that are owned, operated, or provided by HCI Compare LLC. or its subsidiaries, divisions, and affiliates ("HCI Compare LLC", "we", "our" or "us").</p>
<h3>1. Acceptance of Terms and Eligibility</h3>
<ul>
<li><strong>Acceptance:</strong> HCI Compare LLC offers the Service to you conditioned upon your acceptance of all terms, conditions, policies, and notices stated herein or incorporated by reference. By visiting or otherwise using our Service, you acknowledge, accept, and agree to be bound and abide by these Terms and our Privacy Policy.</li>
<li><strong>Age Requirement:</strong> The Service is only offered and available to users who are at least eighteen (18) years of age or older. IF YOU ARE UNDER THE AGE OF EIGHTEEN (18) YOU ARE NOT AUTHORIZED TO USE THE SERVICE.</li>
<li><strong>Right to Change:</strong> We reserve the right to change these Terms at any time at our sole discretion. Any changes will be effective immediately upon posting. Your continued use affirms your agreement to the new Terms.</li>
<li><strong>English Language:</strong> These Terms are written in the English language. To the extent any translated versions conflict with the English version, the English version shall control.</li>
</ul>
<h3>2. Accuracy of Information and Professional Disclaimer</h3>
<ul>
<li><strong>General Information Only:</strong> We built the Service to be a resource for consumers. The information presented is made available solely for general information purposes and is not intended as a substitute for professional or financial advice.</li>
<li><strong>No Professional Relationship:</strong> HCI Compare LLC is not a health insurer, insurance carrier, agent, or broker. We do not issue insurance contracts or bind coverage ourselves, nor do we endorse or recommend any specific companies or policy types.</li>
<li><strong>User Responsibility:</strong> You should not rely upon information on this Service as the sole basis for making decisions without consulting primary, more accurate sources. Always seek the advice of a qualified professional and never disregard professional advice because of something you have read on the Service.</li>
</ul>
<h3>3. Requests and Network Partners</h3>
<ul>
<li><strong>Request Referrals:</strong> By submitting a "Request" for information, you agree to allow us to refer your information to our Network Partners (insurance agents, carriers, aggregators, etc.).</li>
<li><strong>No Guarantee:</strong> We do not guarantee that Network Partners will provide information for every Request or that they can meet your specific requirements. We reserve the right to reject any Request at our sole discretion.</li>
<li><strong>Third-Party Transactions:</strong> Once we refer your Request, we have no further involvement in, or responsibility for, any transactions between you and such Network Partner. We are not liable for any expenses, losses, or damages incurred in such transactions.</li>
</ul>
<h3>4. Accessing the Service and Security</h3>
<ul>
<li><strong>Availability:</strong> We reserve the right to withdraw or amend our Service without notice. We will not be liable if all or any part of the Service is unavailable at any time.</li>
<li><strong>Correct Information:</strong> It is a condition of your use that all information you provide is correct, current, and complete. All information provided is governed by our Privacy Policy.</li>
<li><strong>Identification Responsibility:</strong> YOU ARE SOLELY RESPONSIBLE FOR ALL ACCESS TO AND USE OF THE SERVICE BY ANYONE USING YOUR IDENTIFICATION, WHETHER OR NOT AUTHORIZED BY YOU.</li>
</ul>
<h3>5. Intellectual Property Rights and Ownership</h3>
<ul>
<li><strong>Proprietary Rights:</strong> The Service and its entire contents (including information, software, text, displays, images, video, and audio) are owned by HCI Compare LLC or its licensors and are protected by copyright, trademark, and other intellectual property laws.</li>
<li><strong>Limited License:</strong> These Terms permit you to use the Service for personal, non-commercial use only. You are prohibited from copying, modifying, decompiling, or reverse engineering any Content.</li>
<li><strong>Trademarks:</strong> You must not use our trademarks, logos, or slogans without prior written permission.</li>
</ul>
<h3>6. Linking and Linked Sites</h3>
<ul>
<li><strong>Permission Required:</strong> Creating a link to any portion of the Service or displaying the Service in any format without prior written permission is strictly prohibited.</li>
<li><strong>Third-Party Links:</strong> The Service may provide links to third-party "Linked Sites." HCI Compare LLC does not maintain these sites and is not responsible for their content, accuracy, or security. Your access to Linked Sites is entirely at your own risk.</li>
</ul>
<h3>7. Prohibited Uses</h3>
<ul>
<li><strong>Lawful Use Only:</strong> You agree not to use the Service in any way that violates federal, state, local, or international law.</li>
<li><strong>Specific Prohibitions:</strong> You agree not to:
<ul>
<li>Exploit or harm minors.</li>
<li>Send "junk mail," "spam," or similar solicitations.</li>
<li>Impersonate the company or other users.</li>
<li>Use any robot, spider, or other automatic device to monitor or copy material.</li>
<li>Introduce viruses, Trojan horses, or other malicious material.</li>
</ul>
</li>
</ul>
<h3>8. User Content and Content Standards</h3>
<ul>
<li><strong>Non-Confidentiality:</strong> Other than PII, any creative material, suggestions, or comments you post are non-confidential and non-proprietary.</li>
<li><strong>License Grant:</strong> By providing User Content, you grant us a perpetual, worldwide, irrevocable, royalty-free license to use, reproduce, modify, and distribute such material for any purpose.</li>
<li><strong>Standards:</strong> User Content must comply with all laws and must not be defamatory, obscene, violent, or discriminatory.</li>
<li><strong>Monitoring:</strong> We have the right to remove User Content for any reason and cooperate with law enforcement regarding illegal use.</li>
</ul>
<h3>9. Geographic Restrictions</h3>
<ul>
<li><strong>U.S. Based:</strong> HCI Compare LLC is based in the United States; as such, we provide the Service for use only by persons located in the United States.</li>
<li><strong>Compliance:</strong> We make no claims that the Service or any of its Content is accessible or appropriate outside of the United States. If you access the Service from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</li>
</ul>
<h3>10. SMS/MMS Mobile Messaging Program (2026 Compliance)</h3>
<ul>
<li><strong>Program Details:</strong> By opting into the Program, you agree to receive autodialed or prerecorded marketing messages from us and our Contacts. Consent is not a condition of purchase.</li>
<li><strong>2026 Revocation Standard:</strong> You may revoke your consent at any time via any reasonable means. While you may reply "STOP" to any mobile message to opt out, we also honor other reasonable methods of revocation, including verbal requests to our employees or written requests sent to our support channels.</li>
<li><strong>Processing Time:</strong> We will honor all opt-out requests within ten (10) business days.</li>
<li>Compliance: We endeavor to comply with the TCPA and state telemarketing laws. </li>
</ul>
<h3>11. Disclaimers and Limitation of Liability</h3>
<ul>
<li>YOUR USE OF THE SERVICE IS AT YOUR RISK. THE SERVICE AND ALL SERVICES, INFORMATION, GOODS, AND MATERIALS MADE AVAILABLE OR PURCHASED THROUGH THE SERVICE ARE PROVIDED TO YOU "AS IS" WITHOUT ANY EXPRESS REPRESENTATIONS OR WARRANTIES OF ANY KIND, AND WE DISCLAIM ALL STATUTORY OR IMPLIED REPRESENTATIONS, WARRANTIES, TERMS, AND CONDITIONS WITH RESPECT TO THE SERVICE AND ALL SERVICES, INFORMATION, GOODS, AND MATERIALS MADE AVAILABLE THROUGH THE SERVICE, INCLUDING THE REPRESENTATIONS AND WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, AND TITLE, AND WITH RESPECT TO THE PRODUCTS LISTED OR PURCHASED ON OR THROUGH THE SERVICE.</li>
<li>WE MAKE NO REPRESENTATION OR WARRANTY THAT THE SERVICE (OR ANY PART THEREOF) WILL BE ACCURATE, COMPLETE, OR ERROR-FREE, NOR THAT ANY PARTICULAR SOFTWARE OR HARDWARE, WILL BE COMPATIBLE WITH THE SERVICE, AND YOU HEREBY AGREE THAT IT IS YOUR SOLE RESPONSIBILITY TO (A) OBTAIN AND PAY FOR ANY SOFTWARE, HARDWARE AND SERVICES (INCLUDING INTERNET CONNECTIVITY) NEEDED TO ACCESS AND USE THE SERVICE AND (B) ENSURE THAT ANY SOFTWARE, HARDWARE, AND SERVICES THAT YOU USE WILL FUNCTION CORRECTLY WITH THE SERVICE. THE MATERIALS ON THE SERVICE MAY BE OUT OF DATE, AND HCI Compare LLC MAKES NO COMMITMENT AND ASSUMES NO DUTY TO UPDATE SUCH MATERIALS. HCI Compare LLC MAKES NO WARRANTY THAT THE SERVICE WILL BE AVAILABLE, UNINTERRUPTED, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT YOU WILL ACHIEVE SUCCESSFUL RESULTS FROM FOLLOWING ANY INSTRUCTIONS OR DIRECTIONS ON THE SERVICE. YOU AGREE THAT YOU MUST EVALUATE, AND THAT YOU BEAR ALL RISKS ASSOCIATED WITH, THE USE OF THE SERVICE, INCLUDING ANY RELIANCE ON THE ACCURACY, COMPLETENESS, TIMELINESS, OR USEFULNESS OF ANY INFORMATION OR MATERIALS MADE AVAILABLE THROUGH THE SERVICE. WITHOUT LIMITING THE FOREGOING, HCI Compare LLC HEREBY EXPRESSLY DISCLAIMS ALL LIABILITY FOR PRODUCT DEFECT OR FAILURE, CLAIMS THAT ARE DUE TO NORMAL WEAR, PRODUCT MISUSE, ABUSE, PRODUCT MODIFICATION, IMPROPER PRODUCT SELECTION, NON-COMPLIANCE WITH ANY CODES, OR MISAPPROPRIATION. HCI Compare LLC MAKES NO WARRANTIES TO THOSE DEFINED AS "CONSUMERS" IN THE MAGNUSON-MOSS WARRANTY ACT. THE FOREGOING EXCLUSIONS OF IMPLIED WARRANTIES DO NOT APPLY TO THE EXTENT PROHIBITED BY LAW. </li>
<li>ADDITIONALLY, IN NO EVENT WILL HCI Compare LLC, ITS RESPECTIVE MEMBERS, EMPLOYEES, AFFILIATES, AGENTS, SUCCESSORS, ASSIGNS, RETAIL PARTNERS, OR ANY PARTY INVOLVED IN THE CREATION, PRODUCTION, OR TRANSMISSION OF THE SERVICE, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND IN CONNECTION WITH THE SERVICE, OR FOR ANY DAMAGES FOR LOSS OF PROFITS, LOSS OF USE, LOSS OF DATA, LOSS OF OTHER INTANGIBLES, BUSINESS INTERRUPTION, LOSS OF SECURITY OF INFORMATION YOU HAVE PROVIDED IN CONNECTION WITH YOUR USE OF THE SERVICE, OR UNAUTHORIZED INTERCEPTION OF ANY SUCH INFORMATION BY THIRD PARTIES, EVEN IF ADVISED IN ADVANCE OF SUCH DAMAGES OR LOSSES. FURTHER, WE WILL NOT BE LIABLE FOR DAMAGES OF ANY KIND RESULTING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, ANY INFORMATION OR MATERIALS ON THE SERVICE, ANY LINKED SITES, OR THE MATERIALS, INFORMATION, OR SERVICES CONTAINED AT ANY OR ALL SUCH LINKED SITES. IN THE EVENT OF ANY PROBLEM WITH THE SERVICE OR ANY CONTENT, YOU AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SERVICE IS TO STOP USING THE SERVICE. MOREOVER, IN THE EVENT OF ANY PROBLEM OR DISSATISFACTION WITH THE PRODUCT THAT YOU HAVE PURCHASED ON OR THROUGH THE SERVICE, YOU AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY, IF ANY, IS TO SEEK A RETURN AND REFUND FOR SUCH PRODUCT IN ACCORDANCE WITH THE RETURN POLICY POSTED ON THE SERVICE. OUR MAXIMUM LIABILITY FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE), OR OTHERWISE SHALL BE THE TOTAL AMOUNT, IF ANY, PAID BY YOU TO US TO ACCESS AND USE THE SERVICE. </li>
<li>IT IS POSSIBLE THAT APPLICABLE LAW MAY NOT ALLOW FOR LIMITATIONS ON CERTAIN IMPLIED WARRANTIES OR EXCLUSIONS OR LIMITATIONS OF CERTAIN DAMAGES; SOLELY TO THE EXTENT THAT SUCH LAW APPLIES TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS. IF APPLICABLE LAW PROHIBITS THE LIMITATION OR EXCLUSION OF A PARTY'S LIABILITY WITH RESPECT TO DEATH OR PERSONAL INJURY CAUSED BY SUCH PARTY'S NEGLIGENCE, FRAUD, OR ANY OTHER MATTER, THEN SUCH PARTY'S LIABILITY WILL NOT BE LIMITED OR EXCLUDED TO THE EXTENT OF SUCH PROHIBITION UNDER SUCH APPLICABLE LAW. </li>
<li>If you are a California resident, you agree to consciously waive all claims, both known and unknown that may be later discovered, to the maximum extent permitted by law, including but not limited to that permitted by California Civil Code Section 1542, which states "(a) general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party." </li>
</ul>
<h3>12. Indemnification</h3>
<ul>
<li>Except to the extent prohibited under applicable law, you agree to indemnify, defend, and hold harmless HCI Compare LLC and its officers, directors, employees, and agents from and against any claims, losses, liabilities, damages, costs, or expenses, including attorneys' fees and costs, that may arise from or in connection with (a) your use of, or activities in connection with, the Service, including use of any good, product, or service purchased through the Service, (b) violation of these Terms by you, including any misrepresentations made by you in connection with your use of the Service (c) your violation of any law or the rights of a third-party, and (d) the acts or omissions of any other user or third-party. If you fail to promptly indemnify and defend a covered claim, HCI Compare LLC shall have the right to defend itself, and in such case, you shall promptly reimburse HCI Compare LLC for all of its associated costs and expenses. HCI Compare LLC reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to your indemnification. </li>
</ul>
<h3>13. ARBITRATION, CHOICE OF LAW, AND VENUE</h3>
<ul>
<li>Any dispute, claim, or controversy arising out of or relating to these Terms, including the determination of the scope or applicability of this agreement to arbitrate, shall be submitted to and settled exclusively by binding arbitration, in accordance with the provisions of this section, subject only to any applicable requirement of law that you and HCI Compare LLC engage in a preliminary, non-binding mediation or arbitration. Binding arbitration shall be conducted in accordance with the American Arbitration Association's rules (the "AAA Rules"). Arbitration shall be held in Orange County, Florida, and shall be held before an arbitrator selected pursuant to the AAA Rules who shall have no personal or pecuniary interest, either directly or indirectly, from any business or familial relationship with either you or us. The arbitrator(s) shall be bound to adjudicate all disputes in accordance with the laws of the State of Florida and all decisions of the arbitrator will be final, binding, and conclusive on you and HCI Compare LLC. Either you or HCI Compare LLC may seek confirmation of the arbitration award in the Florida state courts in and for Orange County, Florida, and both parties hereby consent to the exclusive jurisdiction and venue of the Florida state courts in and for Orange County, Florida in any claim or action arising under this arbitration provision. </li>
</ul>