<?php //include '../globalvars.php'; ?>
<h1>Privacy Policy:</h1>
<p>HCI Compare and its subsidiaries (collectively, “healthcare-quotes.com”, “us”, “we”, or “our”) are committed to maintaining your confidence and trust as it relates to the privacy and use of your information. Please read below and learn how we collect, protect, share, and use your information as part of our technology platforms, and all of our products and services.</p>
<p>This privacy policy applies to this site, healthcare-quotes.com, and all other websites owned and operated by us on which this privacy policy is displayed (such websites referred to hereafter as the “Site”, whether individually or collectively). This policy does not apply to websites that post different privacy statements.</p>
<ol>
  <li>Information We Collect
    <ol style="list-style-type:lower-alpha;">
      <li>Personally Identifiable Information: We collect personally identifiable information that can identify you such as your name, address, telephone number, mobile number, email address and zip code, (collectively, “Personally Identifiable Information” or “PII”). PII could also be information you provide concerning others, such as family members.</li>
      <li>Non-Personally Identifiable Information: We also collect information such as demographic data, data about your online activity, data about your income, and other information which could not be used to identify you (including your smoker status, which is used for the limited purpose of providing you with more accurate insurance pricing information) (collectively, “Non-Personally Identifiable Information” or “NPII”).</li>
      <li>Information: PII and NPII are known together as “Information”.</li>
    </ol>
  </li>
  <li>How We Collect Information
    <ol style="list-style-type:lower-alpha;">
      <li>Information provided by you: Information is collected from you when you enter information in connection with an inquiry into our services. This Information could be provided via an online form, over the phone, or via other means through which you interact with our services.</li>
      <li>Information from service providers: Information is also purchased or otherwise collected from third party service providers who may have access to your Information. These third party service providers include our publisher partners to whom you may have submitted your Information. If we acquired all or some of your Information from one of our publisher partners we will use that Information consistently with this privacy policy. We do not control how your Information may be used by the publisher partner to whom you submitted it.</li>
      <li>Information from cookies and other tracking technologies: Like many websites, we use cookies, web beacons, and similar technologies to record your preferences, track the use of our Site and collect information. This information may include but is not limited to internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and/or clickstream data. We may combine this automatically collected log information with other Information we collect about you. Some of this information is collected using tracking technologies provided by third parties and information collected by them for us will be subject to their privacy policies and/or terms of service. Such third parties include but are not limited to Alphabet Inc. (Google analytics product), whose privacy policy can be viewed here: <a target="_blank" href="https://www.google.com/intl/en/policies/privacy/">https://www.google.com/intl/en/policies/privacy/</a>; Active Prospect, whose privacy policy can be viewed here: <a target="_blank" href="https://activeprospect.com/privacy-policy/">https://activeprospect.com/privacy-policy/</a></li>
    </ol>
        Cookies are used for different purposes. They allow you to be recognized as the same user across the different pages of a website, between websites, or when you use an app. Our Site and/or apps use cookies for different purposes:
        Technical Cookies: We try to give our visitors an advanced, user-friendly Site and apps that adapt automatically to their needs and wishes. To achieve this we use technical cookies to show you our Site, to make it function correctly, to create your user account, to sign you in, and to manage your bookings. These technical cookies are absolutely necessary for our Site to function properly.
        Functional Cookies: We also use functional cookies to remember your preferences and help you use our Site and apps efficiently and effectively. For example, these cookies remember your preferred currency, language and your searches. We may also use cookies to remember Information you have provided previously. These functional cookies are not strictly necessary for our Site to work, but they make it easier to use and enhance your experience.
        Analytics Cookies: We use these cookies to gain insight into how our visitors use the Site. This means we can find out what works and what doesn't, optimize and improve our Site or apps, understand the effectiveness of advertisements and communications, and ensure we continue to be interesting and relevant. The data we gather can include which web pages you've viewed, which referring/exit pages you've entered and left from, which platform type you've used, which emails you've opened and acted upon, and date and time stamp info.
        It also means we can use details about how you interacted with the Site, like the number of clicks you make on a given page, your mouse movements and scrolling activity, the search words you use, and the text you enter into various fields. We use analytics cookies as part of our online advertising campaigns to learn how users interact with our Site or apps after they've been shown an online advertisement. This may include advertisements on third-party websites. Analytics cookies may also be used to enable our business partners to learn if their customers use offers integrated into their websites.
        Commercial Cookies: We use third-party cookies as well as our own to display personalized advertisements on our websites and on other websites. This is called “retargeting,” and it's based on browsing activities like the types of health insurance you've been searching for.
  </li>
  <li>How We Use Your Information<br>We may use Information to:
    <ol style="list-style-type:lower-roman;">
      <li>Deliver the products and services you requested, including via our Network Partners (defined below)</li>
      <li>Improve customer service</li>
      <li>Improve our Site</li>
      <li>Personalize your user experience</li>
      <li>Communicate with you about products or services that may be of interest to you</li>
      <li>Manage our business</li>
    </ol>
  </li>
  <li>Who Do We Share Your Information With?
    <ol style="list-style-type:lower-alpha;">
      <li>Affiliate companies: We may share your information with other entities that control, are controlled by or are under common control with HCI Compare, including for the purpose of allowing them to advertise products and services to you. When we share information with these affiliates, they will use and process the information consistently with their applicable privacy policy.</li>
      <li>Network Partners: In submitting an inquiry for a health insurance quote, product or other service provided through the Site, you agree that healthcare-quotes.com may sell to or otherwise share your Information with insurance agents, insurance carriers, lead aggregators, other insurance service providers and other third parties in our network that provide services to our users (collectively, “Network Partners”) to deliver the quotes, products or services your requested. PLEASE NOTE: the Network Partners with which you are matched may retain or use your Information whether or not you use their services. You should contact these Network Partners directly concerning their privacy and information sharing practices.</li>
      <li>healthcare-quotes.com Vendors: We may share your Information with vendors that perform certain services on our behalf (“healthcare-quotes.com Vendors”) including, but not limited to marketing partners (for example, for retargeting purposes), entities providing business analysis and/or website or product support and entities whose services are used to match you with a Network Partner such as boberdoo.com LLC, HCI Compare LLC.</li>
      <li>Other Situations: We may also disclose your Information at our sole discretion:</li>
        <ol style="list-style-type:lower-roman;">
          <li>In response to a subpoena or similar investigative demand, a court order, a request for cooperation from a law enforcement agency, self-regulatory body, or other governmental agency; to establish or exercise our legal rights; to defend against legal claims; to respond to any complaint; or as we reasonably believe is required by law. In such cases, we may raise or waive any legal objection or right available to us.</li>
          <li>When we believe disclosure is appropriate in order to investigate, prevent, or take action regarding actual or suspected illegal activity or other wrongdoing; to protect and defend the rights, property, or safety of healthcare-quotes.com and any healthcare-quotes.com Affiliates, our users, our employees, or others; or to enforce our Site's terms of use or other agreements or policies.</li>
          <li>In connection with a substantial corporate transaction involving healthcare-quotes.com or any healthcare-quotes.com Affiliate, such as a sale of healthcare-quotes.com or any entity, brand or division thereof, a divestiture, merger, consolidation, asset sale, or bankruptcy.</li>
          <li>In connection with state and/or federal licensing or other legal requirements. You authorize healthcare-quotes.com to obtain any and all required information from the Network Partners you were matched with in order for healthcare-quotes.com to comply with current laws and regulations as well as with any requests from state or federal regulators.</li>
          <li>We may share Non-Personally Identifiable Information with third parties in our discretion.</li>
        </ol>
      <li>Trusted Marketing Partners – We reserve the right to share your data with our trusted 3rd party marketing partners. These partners may market to you via email or through other channels, products or services that might be of interest.</li>
    </ol>
  </li>
  <li>Unsubscribe<br>If at any time you do not wish to receive communications from healthcare-quotes.com, you may opt out by following the instructions included in any communication received from us. In addition, you may email <a target="_blank" href="mailto:info@healthcare-quotes.com">info@healthcare-quotes.com</a> to unsubscribe. If you opt out, we may still send you non-marketing emails. Non-marketing emails include emails about our business dealings with you.</li>
  <li>Updating and Accessing Your Information<br>The appropriate method(s) for accessing your Information, if any, will depend on which Site or services you have used. Please contact us at <a target="_blank" href="mailto:info@healthcare-quotes.com">info@healthcare-quotes.com</a> if you have a specific question or request concerning your Information. We are unable to delete all of your Information because some or all of it must be retained by us to demonstrate our compliance with the Telephone Consumer Protection Act and/or other applicable laws.</li>
  <li>How We Protect Your Information
    <ol style="list-style-type:lower-alpha;">
      <li>We take what we believe to be industry standard security measures (including physical, electronic, and procedural measures) to help safeguard your Information from unauthorized access and disclosure. We also require employees to comply with information security safeguards, we use encryption in the transmission of your Information between your system and ours, and we use firewalls and other intrusion detection and prevention controls to help prevent unauthorized persons from gaining access to your Information.</li>
      <li>No system can be completely secure. Accordingly, although we take steps to secure your Information, we cannot guarantee that your Information, searches, or other communication will always remain secure.</li>
    </ol>
  </li>
  <li>Changes to this Privacy Policy<br>
    healthcare-quotes.com has the discretion to update this privacy policy at any time. When we do, we will revise the date at the top of this page. We encourage you to frequently check this page for any changes to stay informed about how we are helping to protect the Information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.<br>
    ActiveProspectActiveProspect<br>
    Privacy Policy - ActiveProspect<br>
    Last modified: 2/20/20 Introduction ActiveProspect, Inc. (“Company”, “We” or “ActiveProspect”) respect your privacy and are committed to protecting it through our compliance with this policy. This policy describes the types of information we may collect…
  </li>
  <li>Visiting our Websites From Outside the United States<br>
    The Site is governed by the laws of the United States, and is intended for the enjoyment of residents of the United States only. We make no representation that the Site is governed by or operated in accordance with the laws of any other nation.</li>
  <li>Compliance with Children's Online Privacy Protection Rule<br>
    We do not knowingly collect, use or disclose personally identifiable information from anyone under 13 years of age. If we determine upon collection that a user is under this age, we will not use or maintain his/her PII without the parent/guardian's consent. If we become aware that we have unknowingly collected PII from a child under the age of 13, we will make reasonable efforts to delete such information from our records.
  </li>
  <li>Your Consent.<br>
    By using our Site, you consent to this privacy policy. If you do not agree to this policy, please do not use any portion of the Site.<br>
    By providing your contact information to us through the Site, you are registering to receive communications from us directly, on our website or through a third party. We will periodically send you newsletters and other e-mails with offers and promotions. You may opt out of commercial e-mails from us by following the instructions in the e-mail or contacting us at the e-mail address below.<br>
    Further, by providing your contact information through the Site, you are authorizing us to share your Information with our Network Partners and third-party vendors as described herein. If you do not want further communication from our Network Partners please notify the partner directly.<br>
    Whether you are contacted by us, a third party on our behalf or a Network Partner, you agree to be contacted through the use of emails or, subject to your express opt-in at time of providing your PII, on your landline or mobile phone by live operators, automated telephone dialing systems, pre-recorded messages, and/or text messages regardless of whether you have placed your name or telephone number on a Do Not Call list. You may stop receiving calls and text messages by following the instructions in those messages. Please note that a stop request will only apply to the specific entity to whom such request is directed.
  </li>
  <li>How to Contact Us<br>
    If you have any questions about this privacy policy, the practices of healthcare-quotes.com, or your dealings with a healthcare-quotes.com affiliate, please contact us at: <a target="_blank" href="mailto:info@healthcare-quotes.com">info@healthcare-quotes.com</a>
  </li>
</ol>